# Generated by Django 3.1.1 on 2020-10-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='finalizada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
