# Generated by Django 3.1.1 on 2020-10-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
