# Generated by Django 3.1.1 on 2020-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0002_projeto_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
